[2023-04-21 09:02:22,436][root][INFO] - 
Overwritten parameters in the config: 
mode=tiling
[2023-04-21 09:02:22,436][root][INFO] - 
---------------------------------------
Let's start tiling for segmentation !!!
---------------------------------------
[2023-04-21 09:02:22,660][matplotlib][DEBUG] - matplotlib data path: C:\Users\abfernan\.conda\envs\geo_deep_env\lib\site-packages\matplotlib\mpl-data
[2023-04-21 09:02:22,668][matplotlib][DEBUG] - CONFIGDIR=C:\Users\abfernan\.matplotlib
[2023-04-21 09:02:22,668][matplotlib][DEBUG] - interactive is False
[2023-04-21 09:02:22,668][matplotlib][DEBUG] - platform is win32
[2023-04-21 09:02:22,724][matplotlib][DEBUG] - CACHEDIR=C:\Users\abfernan\.matplotlib
[2023-04-21 09:02:22,724][matplotlib.font_manager][DEBUG] - Using fontManager instance from C:\Users\abfernan\.matplotlib\fontlist-v330.json
[2023-04-21 09:02:23,180][fiona.session][DEBUG] - Could not import boto3, continuing with reduced functionality.
[2023-04-21 09:02:23,196][fiona._env][DEBUG] - GDAL_DATA found in environment.
[2023-04-21 09:02:23,196][fiona._env][DEBUG] - PROJ_DATA found in environment.
[2023-04-21 09:02:24,364][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_nyhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:24,524][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_gahpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:24,668][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_TN.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:24,804][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_MD.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:25,228][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_MD.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:25,340][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_njhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:25,516][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_gahpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:25,868][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_MD.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:26,028][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_MD.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:26,140][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_njhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:26,316][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_ethpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:26,444][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_mnhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:26,636][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_nbhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:26,756][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_kshpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:26,924][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/ca_nrc_ABCSRSV4.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:27,036][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_emhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:27,156][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_nmhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:27,260][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_azhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:27,396][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_wmhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:27,524][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_uthpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-21 09:02:28,148][root][CRITICAL] - Couldn't locate path: C:\Users\abfernan\CrossCanFloodMapping\DatasetCNNFlood\Class1RawData.csv.
Provided key: raw_data_csv
